# ripgrep configuration file
# enable by point the RIPGREP_CONFIG_PATH environment variable to this file

# Because who cares about case!?
# --smart-case

# Enable hyperlink support starting from v14.0.0
--hyperlink-format=default

# Show files searched, helpful for debugging
# --stats
