# shim_exec.exe 的安装路径
shim_generator_path = "~/.local/bin/shim_exec.exe"
# shim_exec.exe 的 GitHub 仓库
shim_repository = "enihsyou/shim_exectuable"

# 前有 cmd 不支持 shell hook，只认系统环境变量
# 后有 vscode 不加载 pwsh PROFILE，不能在运行时修改 PATH
# 所以需要提前为开发工具设置一个默认版本，这部分已经从各个工具版本管理器交给 vfox shims 目录了
# 这里列出的是其他想要添加到 PATH 的工具

# ==============================================================================
# Shim Groups
# ==============================================================================

[[shim_groups]]
target = "~/.local/bin/"
sources = [
  # jq from winget
  # since jq is installed as a portable binary, winget will add its installation folder to PATH,
  # which bloats the PATH once more, so we shim it, and another entry from PATH is removed.
  "~/AppData/Local/Microsoft/WinGet/Packages/jqlang.jq_Microsoft.Winget.Source_8wekyb3d8bbwe/jq.exe",
  # iperf3 from winget
  "~/AppData/Local/Microsoft/WinGet/Packages/ar51an.iPerf3_Microsoft.Winget.Source_8wekyb3d8bbwe/iperf3.exe",
  # jadx-gui from winget
  "~/AppData/Local/Microsoft/WinGet/Packages/Skylot.jadx_Microsoft.Winget.Source_8wekyb3d8bbwe/jadx-gui-1.5.3.exe",
  # hurl from winget - 从系统级别的环境变量降级到这里
  "~/AppData/Local/Programs/hurl/hurl.exe",
  # msys2 的 make 编译时启用了 --enable-nls，相比 ezwinports.make 额外支持本地化, 但同时也会将默认 shell 从 cmd 改为 sh
  "C:/msys64/usr/bin/make.exe",
  # msys2 packages
  "C:/msys64/usr/bin/rsync.exe",
  "C:/msys64/usr/bin/socat.exe",
  "C:/msys64/usr/bin/telnet.exe",
  "C:/msys64/ucrt64/bin/virsh.exe",
  # vfox from winget - 从系统级别的环境变量降级到这里
  "C:/Program Files/vfox/vfox.exe",
  # GitHub CLI from winget - 从系统级别的环境变量降级到这里
  "C:/Program Files/GitHub CLI/gh.exe",
  # openssl from Git for Windows
  "C:/Program Files/Git/mingw64/bin/openssl.exe",
  "C:/Program Files/Vim/vim91/vim.exe",
  "C:/Program Files/Vim/vim91/gvim.exe",
  "D:/Program Files/imhex/imhex-gui.exe",
  "C:/Program Files/Graphviz/bin/dot.exe",
  # YubiKey Manager CLI - 省去在 PATH 中添加目录
  "C:/Program Files/Yubico/YubiKey Manager CLI/ykman.exe",
  # qemu
  "C:/Program Files/qemu/qemu-system-x86_64.exe",
  "C:/Program Files/qemu/qemu-img.exe",
  "C:/Program Files/qemu/qemu-ga.exe",
]

[[shim_groups]]
target = "~/.version-fox/shims/"
sources = [
  # 使用我们的 shim 版本来替换 version-fox 生成的，启动速度更快
  "~/.version-fox/cache/nodejs/current/node.exe",
]

# ==============================================================================
# Individual Shims (with unique targets or properties)
# ==============================================================================

[[shims]]
# 直接在命令行启动 git-bash
source = "C:/Program Files/Git/bin/sh.exe"
target = "~/.local/bin/git-sh.exe"

[[shims]]
# 在新窗口打开 git-bash
source = "C:/Program Files/Git/git-bash.exe"
target = "~/.local/bin/git-bash.exe"

# ==============================================================================
# Symbolic Link Groups
# ==============================================================================

[[symbolic_link_groups]]
target = "~/.local/bin/"
sources = [
  # Helper to locate Visual Studio installations
  # Some Makefile (like gnu make.git) depends on this to locate the compiler
  # can't be shimmed, since shim created by my shim_exec requires admin permission to run
  "C:/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe",
  "C:/Program Files/7-Zip/7z.exe",
]

# ==============================================================================
# Individual Symbolic Links
# ==============================================================================

[[symbolic_links]]
# see shell/pwsh/PSHelper_Environment.ps1
source = "~/.version-fox/cache/golang/current/bin/go.exe"
target = "~/.version-fox/shims/"
