# Delta settings for Git
# https://github.com/dandavison/delta
# This section configures options for the delta diff tool.
# Conditional included in ~/.gitconfig

[core]
  pager = delta

[interactive]
  diffFilter = delta --color-only

[merge]
  conflictstyle = zdiff3

[diff]
  colorMoved = default

[delta]
  line-numbers = true
  # Open link in vscode
  hyperlinks = true
  hyperlinks-file-link-format = "vscode://file/{path}:{line}"
  side-by-side = true
  # Use n and N to move between diff sections
  navigate = true
  # Assume the terminal supports 24-bit color
  true-color = always
