# code: language=properties
# vim: set filetype=gitconfig

[hub]
  protocol = https

[alias]
  # 看谁提交数最多
  count = !git shortlog -sn

[core]
  # 我们放在 .gitconfig 边上
  excludesfile = ~/.gitignore
  # 尊重文件自身的换行符，兼容多平台
  autocrlf = input
  pager = delta
  # 避免路径内的中文乱码
  quotepath = false
  # 提交时禁止混合换行符
  safecrlf = warn
  sshCommand = ssh -o BatchMode=yes
	symlinks = true

[push]
  # See `git help config` (search for push.default)
  # for more information on different options of the below setting.
  #
  # Setting to git 2.0 default to suppress warning message
  default = simple

[filter "lfs"]
  clean = git-lfs clean -- %f
  smudge = git-lfs smudge -- %f
  process = git-lfs filter-process
  required = true

# Local/private config goes in the include
[include]
  path = ~/.gitconfig-delta
  path = ~/.gitconfig-local
  path = ~/.gitconfig-platform

[pull]
  ff = only
  rebase = true

[rebase]
	autoStash = true
	autoSquash = true

[rerere]
	enabled = true
	autoUpdate = true
