# vim: set filetype=gitconfig

[core]
  # 平台支持文件权限位
  filemode = true

[gpg]
  # 使用 Windows 用户目录的 GPG 数据
  program = /mnt/c/Users/enihsyou/.local/bin/gpg.exe

[credential]
  # 使用 Windows 用户目录的 Git 数据
  helper = /mnt/c/Program\\ Files/Git/mingw64/bin/git-credential-manager.exe
