# vim: set filetype=gitconfig

[hub]
  protocol = https

[alias]
  # 看谁提交数最多
  count = shortlog -sn
  # 日志速览
  loga = log --oneline --graph --all
  # 快速输入长单词
  w = worktree
  s = status

[core]
  # 我们放在 .gitconfig 边上
  excludesfile = ~/.gitignore
  # 尊重文件自身的换行符，不要做多余的改变
  autocrlf = false
  pager = delta
  # 避免路径内的中文乱码
  quotepath = false
  # 提交时禁止混合换行符
  safecrlf = warn
  sshCommand = ssh -o BatchMode=yes

[push]
  # See `git help config` (search for push.default)
  # for more information on different options of the below setting.
  #
  # Setting to git 2.0 default to suppress warning message
  default = simple

[filter "lfs"]
  clean = git-lfs clean -- %f
  smudge = git-lfs smudge -- %f
  process = git-lfs filter-process
  required = true

# Local/private config goes in the include
[include]
  path = ~/.gitconfig-delta
  path = ~/.gitconfig-local
  path = ~/.gitconfig-platform

[pull]
  ff = only
  rebase = true

[rebase]
  autoStash = true
  autoSquash = true

[rerere]
  enabled = true
  autoUpdate = true

# use mirror for faster connection
[url "https://gh-proxy.com/github.com/"]
  insteadOf = https://github.com/
# but keep the original for pushing
[url "https://github.com/"]
  pushInsteadOf = https://github.com/
[submodule]
	recurse = true
