#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
type brew &>/dev/null && brew bundle

# find the installers and run them iteratively

find . -name install.sh -maxdepth 2 | while read installer ; do echo "› ${installer}"; bash -c "${installer}" ; done
