# bun user config
# filepath: ~/.bunfig.toml
#:schema https://json.schemastore.org/bunfig.json

# disable telemetry
telemetry = false

[install]
# set default registry as a string
registry = "https://registry.npmmirror.com"

# default for Workspaces starts from 1.3. Make individual project also use it.
linker = "isolated"
