# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# https://yazi-rs.github.io/docs/tips#dropping-to-shell
[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

# If you also using Yazi on Windows:
[[mgr.prepend_keymap]]
on   = "!"
for  = "windows"
run  = 'shell "powershell.exe" --block'
desc = "Open PowerShell here"

# https://github.com/yazi-rs/plugins/tree/main/toggle-pane.yazi
[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

[[mgr.prepend_keymap]]
on   = "P"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

# https://yazi-rs.github.io/docs/tips#parent-arrow
[[mgr.prepend_keymap]]
on  = "K"
run = "plugin parent-arrow -1"

[[mgr.prepend_keymap]]
on  = "J"
run = "plugin parent-arrow 1"

# enihsyou custom
[[mgr.prepend_keymap]]
on = "?"
run = "help"

[[mgr.prepend_keymap]]
on = ["R", "o"]
desc = "sudo edit"
run = 'shell --block -- sudo vim "$0"'
