# 设置配置范例，开启编辑器的自动补全
"$schema" = 'https://starship.rs/config-schema.json'

format = "$time$all$character"

# 在命令之间插入空行
add_newline = false

# Starship 扫描文件的超时时间（单位：毫秒）。
scan_timeout = 25

# Startship 执行命令的超时时间（单位：毫秒）。
command_timeout = 300

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[cmd_duration]
min_time = 100
show_milliseconds = true
show_notifications = true
min_time_to_notify = 15_000

[git_branch]
symbol = " " # nf-oct-git_branch

[git_status]
deleted = "" # nf-cod-close
ignore_submodules = true

[status]
disabled = false
map_symbol = true
symbol = "❗️"

[time]
disabled = false
format = "[$time]($style) "
