#!/bin/bash
# The file path: $HOME/.config/proxy
# driver program for "Shell Proxy oh-my-zsh plugin"
# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/shell-proxy
# sample usage: PROXY_TYPE=xxx proxy enable
# install jq first, then put a json file in ~/.config/proxy.json with the following content:
# {
#   "your_proxy_type": "http://your_proxy_url"
# }

# if no proxy type specified, fallback to default method.
jq -r '.[$ENV.PROXY_TYPE] // $ENV.SHELLPROXY_URL // ""' ~/.config/proxy.json
