#!/bin/bash
# The file path: $HOME/.config/proxy
# driver program for "Shell Proxy oh-my-zsh plugin"
# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/shell-proxy
# sample usage: PROXY_SOCKS=1 proxy enable

case "$PROXY_TYPE" in
  "bytedance")
    echo "http://bj-rd-proxy.byted.org:3128"
    ;;
  "socks5")
    echo "socks5://localhost:10800"
    ;;
  "clash")
    echo "http://localhost:7890"
    ;;
  *)
    # fallback to plugin default method
    echo "${SHELLPROXY_URL}"
    ;;
esac
