# 注意，有些设置会因为是通过SSH执行而导致在slaves中无法体现，应在hadoop-env.sh中设置

APACHE_HOME=~/Apache
export HADOOP_HOME=$APACHE_HOME/hadoop
export HIVE_HOME=$APACHE_HOME/hive
export HBASE_HOME=$APACHE_HOME/hbase
export KAFKA_HOME=$APACHE_HOME/kafka
export FLUME_HOME=$APACHE_HOME/flume
export SPARK_HOME=$APACHE_HOME/spark
export SQOOP_HOME=$APACHE_HOME/sqoop
export LIVY_HOME=$APACHE_HOME/livy
export ZOOKEEPER_HOME=$APACHE_HOME/zookeeper

APACHE_CONF_HOME=$APACHE_HOME/conf
export HADOOP_CONF_DIR=$APACHE_CONF_HOME/hadoop
export HIVE_CONF_DIR=$APACHE_CONF_HOME/hive
export HBASE_CONF_DIR=$APACHE_CONF_HOME/hive
export SPARK_CONF_DIR=$APACHE_CONF_HOME/spark
export LIVY_CONF_DIR=$APACHE_CONF_HOME/livy
export ZOOCFGDIR=$APACHE_CONF_HOME/zookeeper
export KMS_CONFIG=$APACHE_CONF_HOME

export PATH=$HADOOP_HOME/bin:$HIVE_HOME/bin:$HBASE_HOME/bin:$KAFKA_HOME/bin:$FLUME_HOME/bin:$SPARK_HOME/bin:$SQOOP_HOME/bin:$ZOOKEEPER_HOME/bin:$PATH
